f5-tmm:
  enabled: true
  tmm:
    replicaCount: 1
    cniNetworks: ""

    pod:
      annotations:
        k8s.v1.cni.cncf.io/networks: clientside,serverside

    topologyManager: "true"

    add_k8s_routes: true

    image:
      repository: repo.f5.com/images
      pullPolicy: IfNotPresent
    serviceAccount:
      create: false
      name: sa-f5-cnf-cgnat-controller
    persistence:
      enabled: true
      storageclassname: local-path
    customEnvVars:
      # - name: ROBIN_VFIO_RESOURCE_0
      #   value: SRIOV0_VFIOPCI
      # - name: ROBIN_VFIO_RESOURCE_1
      #   value: SRIOV1_VFIOPCI
      # - name: ROBIN_VFIO_RESOURCE_2
      #   value: SRIOV2_VFIOPCI
      # - name: ROBIN_VFIO_RESOURCE_3
      #   value: SRIOV3_VFIOPCI
      # Use the following environment vars
      - name: TMM_MAPRES_VERBOSITY
        value: 'debug'
      - name: TMM_MAPRES_ADDL_VETHS_ON_DP
        value: "TRUE"
        #    - name: TMM_MAPRES_PREFER_SOCK
        #      value: "TRUE"
      - name: TMM_MAPRES_DELAY_MS
        value: '6000'
      - name: TMM_CALICO_ROUTER
        value: "default"
      - name: TMM_IGNORE_GATEWAYS
        value: 'FALSE'
        # - name: GRPC_USE_VAULT
        #   value: 'FALSE'
      - name: TMM_MAPRES_HUGEPAGES
        value: '1536'
        #    - name: REDIS_CA_FILE
        #      value: /etc/ssl/certs/dssm-ca.crt
        #    - name: REDIS_AUTH_CERT
        #      value: /etc/ssl/certs/dssm-cert.crt
        #    - name: REDIS_AUTH_KEY
        #      value: /etc/ssl/private/dssm-key.key
        #    - name: SESSIONDB_EXTERNAL_STORAGE
        #      value: "true"
      - name: SSL_SERVERSIDE_STORE
        value: "/tls/tmm/mds/clt"
      - name: SSL_TRUSTED_CA_STORE
        value: "/tls/tmm/mds/clt"
      - name: SESSIONDB_DISCOVERY_SENTINEL
        value: "true"
      - name: SESSIONDB_EXTERNAL_SERVICE
        value: f5-dssm-sentinel.cnf-gateway
      - name: TMM_MAPRES_USE_VETH_NAME
        value: "TRUE"
        # Commented as in ulises' installation
        #    - name: TMM_MAPRES_IGNORE_VETH
        #      value: "TRUE"
      - name: CONFIG_VIEWER_ENABLE
        value: "TRUE"
        # icni2:
          # enabled: true
    network:
      vfio:
        enabled: true
      bfdToOVN:
       enabled: true

    # dynamicRouting:
    #     enabled: false
    #     configMapName: "zebos"
    #     peerGroups: []
    #     exportZebosLogs: true
    #     tmmRouting:
    #       image:
    #         repository: repo.f5.com/images
    #         initName: f5dr-img-init
    #         pullPolicy: IfNotPresent
    #     tmrouted:
    #       image:
    #         repository: repo.f5.com/images
    #         pullPolicy: IfNotPresent

    service:
      type: ClusterIP
    sessiondb:
      useExternalStorage: "true"
    robinNetworks: "false"
  blobd:
    image:
      repository: repo.f5.com/images
      pullPolicy: IfNotPresent
    enabled: true
    name: f5-blobd

  debug:
    enabled: true
    image:
      repository: repo.f5.com/images
      pullPolicy: IfNotPresent
    rabbitmqNamespace: cnf-gateway
      
  f5-toda-logging:
    enabled: true
    tmstats:
      enabled: true
      config:
        image:
          repository: repo.f5.com/images
          pullPolicy: IfNotPresent
    fluentd:
      host: f5-toda-fluentd.cnf-gateway.svc.cluster.local
    sidecar:
      name: f5-toda-fluentbit
      image:
        repository: repo.f5.com/images
        pullPolicy: IfNotPresent

f5-stats_collector:
  enabled: true
  image:
    repository: repo.f5.com/images
    pullPolicy: IfNotPresent
  exporters:
    prometheus:
      tls:
        client_ca_file: /external/otelsvr/ca.crt
        cert_file: /external/otelsvr/tls.crt
        key_file: /external/otelsvr/tls.key

  imageCredentials:
    name: far-secret

  stats_collector:
    image:
      repository: repo.f5.com/images
      pullPolicy: IfNotPresent
    serviceAccount:
      create: false
      name: sa-f5-cnf-cgnat-controller

  serviceAccount:
    create: false
    name: sa-f5-cnf-cgnat-controller

  rbac:
    create: false
  global:
    serviceAccount:
      create: false
      name: sa-f5-cnf-cgnat-controller

global:
  serviceAccount:
    create: false
    name: sa-f5-cnf-cgnat-controller
  afm:
    enabled: true
    pccd:
      enabled: true
  ipsd:
    enabled: true
  imageCredentials:
    name: far-secret

f5-afm:
  enabled: true
  afm:
    rbac:
      create: true
    serviceAccount:
      create: false
      name: sa-f5-cnf-cgnat-controller
    pccd:
      enabled: true
      image:
        repository: repo.f5.com/images
        pullPolicy: IfNotPresent


    fluentbit_sidecar:
      debug: true
      enabled: true
      image:
        repository: repo.f5.com/images
        pullPolicy: IfNotPresent
      fluentd:
        host: f5-toda-fluentd.cnf-gateway.svc.cluster.local

  imageCredentials:
    name: far-secret

f5-ipsd:
  enabled: true

  ipsd:
    enabled: true
    debug: false
    
    image:
      repository: repo.f5.com/images
      pullPolicy: IfNotPresent
    fluentbit_sidecar:
      debug: true
      enabled: true
      image:
        repository: repo.f5.com/images
        pullPolicy: IfNotPresent    
      fluentd:
        host: f5-toda-fluentd.cnf-gateway.svc.cluster.local

controller:
  tmm_pod_manager:
    image:
      repository: repo.f5.com/images
  image:
    repository: repo.f5.com/images
    pullPolicy: IfNotPresent
  serviceAccount:
    create: false
    name: sa-f5-cnf-cgnat-controller
  f5_lic_helper:
    enabled: true
    rabbitmqNamespace: cnf-gateway
    image:
      repository: repo.f5.com/images
      pullPolicy: IfNotPresent

  fluentbit_sidecar:
    debug: true
    enabled: true
    name: fluentbit
    image:
      repository: repo.f5.com/images
      pullPolicy: IfNotPresent

    fluentd:
      host: f5-toda-fluentd.cnf-gateway.svc.cluster.local

  watchNamespace: cnf-gateway

rbac:
  create: true

imageCredentials:
  name: far-secret
