imageCredentials:
  name: far-secret
replicaCount: 1
nodeSelector:
   type: control-plane
image:
  repository: repo.f5.com/images
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

pod:
  annotations: {}


affinity: {}
