f5-tmm:
  enabled: true
  tmm:
    replicaCount: 1
    cniNetworks: ""

    pod:
      annotations:
        k8s.v1.cni.cncf.io/networks: clientside,serverside
    nodeSelector:
        ## This label is used to deploy the pod on matching nodes
        type: data-plane
    topologyManager: "true"

    add_k8s_routes: true

    image:
      repository: repo.f5.com/images
      pullPolicy: IfNotPresent
    serviceAccount:
      create: false
      name: sa-f5-cnf-cgnat-controller-ingress
    persistence:
      enabled: true
      storageclassname: local-path

    resources:
      limits:
        cpu: "1"
        hugepages-2Mi: 3Gi
        memory: 4Gi
      requests:
        cpu: "250m"
        hugepages-2Mi: 3Gi
        memory: 4Gi  
    customEnvVars:
      - name: TMM_MAPRES_VERBOSITY
        value: 'debug'
      - name: TMM_MAPRES_ADDL_VETHS_ON_DP
        value: "TRUE"
      # - name: TMM_MAPRES_DELAY_MS
      #   value: "20000"
      - name: TMM_CALICO_ROUTER
        value: "default"
      - name: TMM_IGNORE_GATEWAYS
        value: 'true'
        # - name: GRPC_USE_VAULT
        #   value: 'FALSE'
      - name: TMM_MAPRES_HUGEPAGES
        value: '1536'
        #    - name: REDIS_CA_FILE
        #      value: /etc/ssl/certs/dssm-ca.crt
        #    - name: REDIS_AUTH_CERT
        #      value: /etc/ssl/certs/dssm-cert.crt
        #    - name: REDIS_AUTH_KEY
        #      value: /etc/ssl/private/dssm-key.key
        #    - name: SESSIONDB_EXTERNAL_STORAGE
        #      value: "true"
      - name: SSL_SERVERSIDE_STORE
        value: "/tls/tmm/mds/clt"
      - name: SSL_TRUSTED_CA_STORE
        value: "/tls/tmm/mds/clt"
      - name: SESSIONDB_DISCOVERY_SENTINEL
        value: "true"
      - name: SESSIONDB_EXTERNAL_SERVICE
        value: f5-dssm-sentinel.cnf-gateway
      - name: TMM_MAPRES_USE_VETH_NAME
        value: "TRUE"
        # Commented as in ulises' installation
        #    - name: TMM_MAPRES_IGNORE_VETH
        #      value: "TRUE"
      - name: CONFIG_VIEWER_ENABLE
        value: "TRUE"
        # icni2:
          # enabled: true
    network:
      vfio:
        enabled: true

    bfdToOVN:
      enabled: true

    dynamicRouting:
        enabled: true
        configMapName: "cnf-bgp"
        peerGroups: []
        exportZebosLogs: true
        tmmRouting:
          image:
            repository: repo.f5.com/images
            initName: f5dr-img-init
            pullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 150m
              memory: 512Mi
          config:
            bgp:
              asn: 65002
        tmrouted:
          image:
            repository: repo.f5.com/images
            pullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 150m
              memory: 512Mi

    service:
      type: ClusterIP
    sessiondb:
      useExternalStorage: "true"
    robinNetworks: "false"
  blobd:
    image:
      repository: repo.f5.com/images
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 250m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 1Gi
    enabled: true
    name: f5-blobd

  debug:
    enabled: true
    image:
      repository: repo.f5.com/images
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 250m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 1Gi
    rabbitmqNamespace: cnf-gateway
      
  f5-toda-logging:
    enabled: true
    tmstats:
      enabled: true
      config:
        image:
          repository: repo.f5.com/images
          pullPolicy: IfNotPresent
      resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 1Gi
    fluentd:
      host: f5-toda-fluentd.cnf-gateway.svc.cluster.local
    sidecar:
      name: f5-toda-fluentbit
      image:
        repository: repo.f5.com/images
        pullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 250m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 1Gi

f5-stats_collector:
  enabled: true
  image:
    repository: repo.f5.com/images
    pullPolicy: IfNotPresent
  exporters:
    prometheus:
      tls:
        client_ca_file: /external/otelsvr/ca.crt
        cert_file: /external/otelsvr/tls.crt
        key_file: /external/otelsvr/tls.key

  imageCredentials:
    name: far-secret
  nodeSelector:
        ## This label is used to deploy the pod on matching nodes
    type: control-plane

  stats_collector:
    image:
      repository: repo.f5.com/images
      pullPolicy: IfNotPresent
    serviceAccount:
      create: false
      name: sa-f5-cnf-cgnat-controller-ingress

  serviceAccount:
    create: false
    name: sa-f5-cnf-cgnat-controller-ingress
  

global:
  serviceAccount:
    create: false
    name: sa-f5-cnf-cgnat-controller-ingress
  afm:
    enabled: true
    pccd:
      enabled: true
  ipsd:
    enabled: true
  imageCredentials:
    name: far-secret

f5-afm:
  enabled: true
  afm:
    serviceAccount:
      create: false
      name: sa-f5-cnf-cgnat-controller-ingress
    nodeSelector:
      ## This label is used to deploy the pod on matching nodes
      type: control-plane
    pccd:
      enabled: true
      image:
        repository: repo.f5.com/images
        pullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 200m
          memory: 512Mi

    fluentbit_sidecar:
      debug: true
      enabled: true
      image:
        repository: repo.f5.com/images
        pullPolicy: IfNotPresent
      fluentd:
        host: f5-toda-fluentd.cnf-gateway.svc.cluster.local

  imageCredentials:
    name: far-secret

f5-ipsd:
  enabled: true

  ipsd:
    enabled: true
    debug: false
    
    image:
      repository: repo.f5.com/images
      pullPolicy: IfNotPresent
    nodeSelector:
      ## This label is used to deploy the pod on matching nodes
      type: control-plane
    fluentbit_sidecar:
      debug: true
      enabled: true
      image:
        repository: repo.f5.com/images
        pullPolicy: IfNotPresent    
      fluentd:
        host: f5-toda-fluentd.cnf-gateway.svc.cluster.local

controller:
  tmm_pod_manager:
    image:
      repository: repo.f5.com/images
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 512Mi
    nodeSelector:
      ## This label is used to deploy the pod on matching nodes
      type: control-plane
  image:
    repository: repo.f5.com/images
    pullPolicy: IfNotPresent
  nodeSelector:
       ## This label is used to deploy the pod on matching nodes
      type: control-plane
  serviceAccount:
    create: false
    name: sa-f5-cnf-cgnat-controller-ingress
  f5_lic_helper:
    enabled: true
    rabbitmqNamespace: cnf-gateway
    image:
      repository: repo.f5.com/images
      pullPolicy: IfNotPresent

  fluentbit_sidecar:
    debug: true
    enabled: true
    name: fluentbit
    image:
      repository: repo.f5.com/images
      pullPolicy: IfNotPresent
    resources:
      # limits: {}
      #   cpu: 200m
      #   memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    fluentd:
      host: f5-toda-fluentd.cnf-gateway.svc.cluster.local

  watchNamespace: cnf-gateway

rbac:
  create: true

serviceAccount:
  name: sa-f5-cnf-cgnat-controller-ingress

imageCredentials:
  name: far-secret
