---
apiVersion: k8s.f5net.com/v1
kind: F5BigDnsCache
metadata:
  name: dnsc-transparent
spec:
  cacheType: transparent
  transparent:
    msgCacheSize: 100000000
    rrsetCacheSize: 250000000
    rrsetRotate: query-id
---
apiVersion: k8s.f5net.com/v1
kind: F5BigDnsApp
metadata:
  name: vs-dns-transparent
spec:
  destination:
    port: 53
    ipv6Address: 2403:5808:81:50::20
  snat:
    type: automap
  ipProtocol: udp
  dns:
    dnsCache: dnsc-transparent
    dns64Mode:  secondary
    dns64Prefix:  "64:ff9b::"
    dns64AdditionalSectionRewrite: "v4-only"
  vlans:
    disableListedVlans: false
    vlanList:
      - "clientside-vlan"
  pool:
    members:
      - address: 8.8.8.8
        priorityGroup: 1
        port: 53
      - address: 1.1.1.1
        priorityGroup: 1
        port: 53
    minActiveMembers: 1
  monitors:
    icmp:
      enabled: true
      interval: 2
      timeout: 7