---
apiVersion: k8s.f5net.com/v1
kind: F5BigNatPolicy
metadata:
  name: natpol-64
spec:
  sourceTranslation:
    - name: st-v6v4
      routeAdvertisement: true
      icmpEcho: true
      addresses:
        - "10.1.50.0/24"
      excludeAddresses:
        - "10.1.50.0-10.1.50.20"
      clientConnectionLimit: 2000
      mapping:
        mode: endpoint-independent-mapping
      port: 1025-65535
      type: dynamic-pat
  rule:
    - name: rl-nat-any
      ipProtocol: any
      source:
        addresses:
          - "2403:5808:81:10::0/64"
      destination:
        addresses:
         - "2403:5808:81:60::0/96"
      sourceTranslation: st-v6v4
