---
apiVersion: k8s.f5net.com/v1
kind: F5BigNetStaticroute
metadata:
  name: sr-google-dns
spec:
  destination: 8.8.8.8
  prefixLen: 32
  type: gateway
  gateway: 10.1.30.1
---
apiVersion: k8s.f5net.com/v1
kind: F5BigNetStaticroute
metadata:
  name: sr-cloudflare-dns
spec:
  destination: 1.1.1.1
  prefixLen: 32
  type: gateway
  gateway: 10.1.30.1
---
apiVersion: k8s.f5net.com/v1
kind: F5BigNetStaticroute
metadata:
  name: sr-cluster-cidr
spec:
  destination: 10.253.0.0
  prefixLen: 16
  type: gateway
  gateway: 169.254.1.1
  #interface: eth0
---
apiVersion: k8s.f5net.com/v1
kind: F5BigNetStaticroute
metadata:
  name: sr-pod-cidr
spec:
  destination: 192.168.0.0
  prefixLen: 16
  type: gateway
  gateway: 169.254.1.1
  #interface: eth0